security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$BHtKCMPFlt6V/u0E6S.OIuEQT7DurQGLgVB7svbXRIK7OyYXUaThm'
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: admin_in_memory
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /products
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10